### ISSUE TITLE
Feature Request: Expense Rollover

### ISSUE THREAD

**Issue by ouhakheme** [linuxserver/budge#5]
Hello!  If possible, it'd be great to allow for negative envelope balances to rollover to the next month.  The common use case is a friend or employer paying you back in a month after the money was debited.

Snapshot of how a different app handles this:
![2022-02-17 at 08 38](https://user-images.githubusercontent.com/45299405/154493203-374e02e4-2a5d-4253-971d-7eb4d63b2cec.png)

Potentially, this can be an 'advanced feature' use at your own risk.

Thanks!

**Comment by alex-phillips** [comment]
@ouhakheme Just FYI - a form of this is being worked on (and almost complete) here: https://github.com/linuxserver/budge/tree/feature/underfunded-carryover

Instead of carrying over a negative balance to the next month, it will actually attempt to deduct the underfunded amount from the following month's available to budget. If this proves difficult with the cascading of amounts from month-to-month, I may handle it as it does in your example instead.

**Comment by alex-phillips** [comment]
This is now added in 0.0.5. Thanks for the suggestion!
